import re
from datetime import date

import pandas as pd
import streamlit as st

from database import (
    create_tables,
    seed_demo_users,
    create_user,
    verify_password,
    get_user_by_email,
    add_record,
    get_records_by_user,
    update_record,
    delete_record
)
from predictor import generate_health_remark, calculate_health_score


def valid_email(email):
    return re.match(r"^[\w\.-]+@[\w\.-]+\.\w+$", email)


def valid_phone(phone):
    return re.match(r"^[6-9]\d{9}$", phone)


def records_dataframe(records):
    return pd.DataFrame(
        records,
        columns=[
            "ID",
            "Full Name",
            "Date of Birth",
            "Email",
            "Glucose",
            "Haemoglobin",
            "Cholesterol",
            "Remarks",
            "Created At"
        ]
    )


def remarks_box(remarks):
    st.markdown(
        f"""
        <div style="
            background:#f8fbff;
            padding:20px;
            border-radius:15px;
            border-left:5px solid #0b7285;
            color:#12343b;
            line-height:1.7;
            margin-top:10px;
        ">
        <pre style="white-space: pre-wrap; font-family: inherit; margin:0;">{remarks}</pre>
        </div>
        """,
        unsafe_allow_html=True
    )


def report_text(user, row):
    return f"""
HealthIQ Patient Health Assessment Report

Patient Name: {row['Full Name']}
Date of Birth: {row['Date of Birth']}
Email Address: {row['Email']}

Blood Test Values:
Glucose: {row['Glucose']}
Haemoglobin: {row['Haemoglobin']}
Cholesterol: {row['Cholesterol']}

AI/ML Health Remarks:
{row['Remarks']}

Generated for: {user[1]}
Generated by: HealthIQ Predictor
Developed by Radhika Chopra
"""


st.set_page_config(
    page_title="HealthIQ Predictor",
    page_icon="🩺",
    layout="wide"
)

create_tables()
seed_demo_users()

st.markdown("""
<style>
.stApp {
    background: linear-gradient(135deg, #f7fbff 0%, #eef9ff 45%, #ffffff 100%);
}
.hero {
    padding: 36px;
    border-radius: 28px;
    background: linear-gradient(135deg, #e6f7ff, #ffffff);
    border: 1px solid #cdefff;
    box-shadow: 0 12px 35px rgba(0, 91, 128, 0.10);
}
.hero h1 {
    font-size: 46px;
    color: #0b3954;
    margin-bottom: 6px;
}
.hero p {
    color: #41616f;
    font-size: 18px;
}
.card {
    padding: 22px;
    border-radius: 22px;
    background: white;
    border: 1px solid #e3f2f8;
    box-shadow: 0 8px 25px rgba(0, 91, 128, 0.08);
}
.footer {
    position: fixed;
    right: 18px;
    bottom: 10px;
    color: #8aa1ad;
    font-size: 12px;
}
</style>

<div class="hero">
<h1>HealthIQ Predictor</h1>
<p>AI-assisted patient blood test record management with CRUD operations, validation, health-risk remarks and downloadable reports.</p>
</div>

<div class="footer">Developed by Radhika Chopra</div>
""", unsafe_allow_html=True)

if "logged_in" not in st.session_state:
    st.session_state.logged_in = False
    st.session_state.user = None

if not st.session_state.logged_in:
    st.write("")

    tab1, tab2, tab3 = st.tabs(["Login", "Create Account", "Demo Access"])

    with tab1:
        st.subheader("Patient Login")

        email = st.text_input("Email Address", key="login_email")
        password = st.text_input("Password", type="password", key="login_password")

        if st.button("Login"):
            user = verify_password(email, password)

            if user:
                st.session_state.logged_in = True
                st.session_state.user = user
                st.rerun()
            else:
                st.error("Invalid email or password.")

    with tab2:
        st.subheader("Create New Account")

        full_name = st.text_input("Full Name", key="signup_name")
        email = st.text_input("Email Address", key="signup_email")
        phone = st.text_input("Phone Number", key="signup_phone")
        password = st.text_input("Create Password", type="password", key="signup_password")

        if st.button("Create Account"):
            if not full_name.strip():
                st.error("Full Name is required.")
            elif not valid_email(email):
                st.error("Enter a valid email address.")
            elif not valid_phone(phone):
                st.error("Enter a valid 10-digit Indian phone number.")
            elif len(password) < 6:
                st.error("Password must contain at least 6 characters.")
            elif get_user_by_email(email):
                st.error("This email is already registered.")
            else:
                create_user(full_name, email, phone, password)
                st.success("Account created successfully. Please login now.")

    with tab3:
        st.subheader("Demo Access")
        st.info("Use demo access to quickly test the application.")

        c1, c2 = st.columns(2)

        with c1:
            if st.button("Login as Anuj"):
                user = get_user_by_email("anuj.demo@example.com")
                st.session_state.logged_in = True
                st.session_state.user = user
                st.rerun()

        with c2:
            if st.button("Login as Keshav"):
                user = get_user_by_email("keshav.demo@example.com")
                st.session_state.logged_in = True
                st.session_state.user = user
                st.rerun()

else:
    user = st.session_state.user

    st.write("")
    st.markdown(f"### Welcome, {user[1]}")

    if st.button("Logout"):
        st.session_state.logged_in = False
        st.session_state.user = None
        st.rerun()

    dashboard, add_tab, view_tab, update_tab, delete_tab = st.tabs(
        ["Dashboard", "Add Record", "View & Download", "Update Record", "Delete Record"]
    )

    with dashboard:
        records = get_records_by_user(user[0])
        df = records_dataframe(records) if records else pd.DataFrame()

        if not df.empty:
            latest = df.iloc[0]

            score, risk = calculate_health_score(
                latest["Glucose"],
                latest["Haemoglobin"],
                latest["Cholesterol"]
            )

            c1, c2, c3 = st.columns(3)

            with c1:
                st.markdown(
                    f"<div class='card'><h4>Total Records</h4><h2>{len(df)}</h2></div>",
                    unsafe_allow_html=True
                )

            with c2:
                st.markdown(
                    f"<div class='card'><h4>Latest Health Score</h4><h2>{score}/100</h2></div>",
                    unsafe_allow_html=True
                )

            with c3:
                st.markdown(
                    f"<div class='card'><h4>Risk Level</h4><h2>{risk}</h2></div>",
                    unsafe_allow_html=True
                )

            st.write("")
            st.subheader("Latest Health Remarks")
            remarks_box(latest["Remarks"])

            st.write("")
            st.subheader("Health Trend")

            chart_df = df.sort_values("Created At")[
                ["Created At", "Glucose", "Haemoglobin", "Cholesterol"]
            ]

            st.line_chart(chart_df.set_index("Created At"))

        else:
            st.info("No health records available yet. Add your first blood test record.")

    with add_tab:
        st.subheader("Add Patient Blood Test Record")

        with st.form("add_record_form"):
            c1, c2 = st.columns(2)

            with c1:
                full_name = st.text_input("Full Name", value=user[1])
                dob = st.date_input(
                    "Date of Birth",
                    min_value=date(1900, 1, 1),
                    max_value=date.today()
                )
                email = st.text_input("Email Address", value=user[2])

            with c2:
                glucose = st.number_input("Glucose", min_value=0.0, step=1.0)
                haemoglobin = st.number_input("Haemoglobin", min_value=0.0, step=0.1)
                cholesterol = st.number_input("Cholesterol", min_value=0.0, step=1.0)

            submit = st.form_submit_button("Generate Remarks & Save")

            if submit:
                if not full_name.strip():
                    st.error("Full Name is required.")
                elif dob > date.today():
                    st.error("Date of Birth cannot be a future date.")
                elif not valid_email(email):
                    st.error("Enter a valid email address.")
                elif glucose <= 0 or haemoglobin <= 0 or cholesterol <= 0:
                    st.error("Blood test values must be numeric and greater than zero.")
                else:
                    remarks = generate_health_remark(glucose, haemoglobin, cholesterol)

                    add_record(
                        user[0],
                        full_name,
                        str(dob),
                        email,
                        glucose,
                        haemoglobin,
                        cholesterol,
                        remarks
                    )

                    st.success("Record saved successfully.")
                    remarks_box(remarks)

    with view_tab:
        st.subheader("Patient Records")

        records = get_records_by_user(user[0])

        if records:
            df = records_dataframe(records)

            search = st.text_input("Search by name or email")

            if search:
                df = df[
                    df["Full Name"].str.contains(search, case=False, na=False)
                    | df["Email"].str.contains(search, case=False, na=False)
                ]

            st.dataframe(df, use_container_width=True, hide_index=True)

            csv_data = df.to_csv(index=False).encode("utf-8")

            st.download_button(
                "Download Records as CSV",
                data=csv_data,
                file_name="patient_records.csv",
                mime="text/csv"
            )

            selected_report_id = st.selectbox(
                "Select record for report download",
                df["ID"].tolist()
            )

            selected_row = df[df["ID"] == selected_report_id].iloc[0]

            st.download_button(
                "Download Health Assessment Report",
                data=report_text(user, selected_row),
                file_name=f"health_report_{selected_report_id}.txt",
                mime="text/plain"
            )

        else:
            st.info("No records found.")

    with update_tab:
        st.subheader("Update Patient Record")

        records = get_records_by_user(user[0])

        if records:
            df = records_dataframe(records)

            selected_id = st.selectbox(
                "Select Record ID",
                df["ID"].tolist(),
                key="update_select"
            )

            record = df[df["ID"] == selected_id].iloc[0]

            with st.form("update_form"):
                c1, c2 = st.columns(2)

                with c1:
                    full_name = st.text_input("Full Name", record["Full Name"])
                    dob = st.date_input(
                        "Date of Birth",
                        pd.to_datetime(record["Date of Birth"]).date()
                    )
                    email = st.text_input("Email Address", record["Email"])

                with c2:
                    glucose = st.number_input(
                        "Glucose",
                        min_value=0.0,
                        value=float(record["Glucose"]),
                        step=1.0
                    )
                    haemoglobin = st.number_input(
                        "Haemoglobin",
                        min_value=0.0,
                        value=float(record["Haemoglobin"]),
                        step=0.1
                    )
                    cholesterol = st.number_input(
                        "Cholesterol",
                        min_value=0.0,
                        value=float(record["Cholesterol"]),
                        step=1.0
                    )

                update_submit = st.form_submit_button("Update Record")

                if update_submit:
                    if not full_name.strip():
                        st.error("Full Name is required.")
                    elif dob > date.today():
                        st.error("Date of Birth cannot be a future date.")
                    elif not valid_email(email):
                        st.error("Enter a valid email address.")
                    elif glucose <= 0 or haemoglobin <= 0 or cholesterol <= 0:
                        st.error("Blood test values must be numeric and greater than zero.")
                    else:
                        remarks = generate_health_remark(glucose, haemoglobin, cholesterol)

                        update_record(
                            selected_id,
                            full_name,
                            str(dob),
                            email,
                            glucose,
                            haemoglobin,
                            cholesterol,
                            remarks
                        )

                        st.success("Record updated successfully.")
                        remarks_box(remarks)

        else:
            st.info("No records available to update.")

    with delete_tab:
        st.subheader("Delete Patient Record")

        records = get_records_by_user(user[0])

        if records:
            df = records_dataframe(records)

            selected_id = st.selectbox(
                "Select Record ID to Delete",
                df["ID"].tolist(),
                key="delete_select"
            )

            selected = df[df["ID"] == selected_id].iloc[0]

            st.warning(
                f"You are about to delete record ID {selected_id} for {selected['Full Name']}."
            )

            if st.button("Delete Record"):
                delete_record(selected_id)
                st.success("Record deleted successfully.")
                st.rerun()

        else:
            st.info("No records available to delete.")